project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: teaching.qmd
        text: Teaching

page-footer:
  right: "&copy; 2024, Masato Ishizuka"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    

execute: 
  freeze: auto
